name: Copy NDK Asset from Matrix1999
on:
  workflow_dispatch:

jobs:
  copy-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Download asset from Matrix1999
        run: |
          curl -L --retry 3 -o android-ndk-r28c-ollvm.tar.xz             "https://github.com/Matrix1999/ollvm-19/releases/download/android-ndk-ollvm/android-ndk-r28c-ollvm.tar.xz"
          ls -lh android-ndk-r28c-ollvm.tar.xz

      - name: Upload asset to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REL_ID=362582719
          curl -X POST             -H "Authorization: token $GH_TOKEN"             -H "Content-Type: application/x-xz"             --data-binary @android-ndk-r28c-ollvm.tar.xz             "https://uploads.github.com/repos/Matrixzat/ollvm-19/releases/${REL_ID}/assets?name=android-ndk-r28c-ollvm.tar.xz"
          echo "Done"
